import streamlit as st
import google.generativeai as genai
import requests
import urllib.parse

# --- STABLE MODEL CONFIGURATION ---
# Using the stable, high-speed Flash engine for ALL tools to bypass free-tier blocks
MODEL_NAME = "gemini-1.5-flash"

# --- PAGE CONFIG ---
st.set_page_config(page_title="Aura AI | Studio", page_icon="🌀", layout="wide")

# --- PREMIUM SaaS UI (CSS) ---
st.markdown("""
    <style>
    #MainMenu, header, footer, .stDeployButton {visibility: hidden;}
    .stApp { background-color: #F8FAF8; }
    
    .navbar {
        position: fixed; top: 0; left: 0; width: 100%;
        background: rgba(255, 255, 255, 0.9); backdrop-filter: blur(12px);
        padding: 15px 40px; z-index: 9999; display: flex; align-items: center;
        border-bottom: 1px solid #4F46E533; box-shadow: 0 4px 12px rgba(0,0,0,0.03);
    }
    .spinning-logo {
        width: 32px; height: 32px; border: 4px solid #4F46E5;
        border-top: 4px solid transparent; border-radius: 50%;
        animation: spin 2s linear infinite; margin-right: 15px;
    }
    @keyframes spin { 100% { transform: rotate(360deg); } }
    .brand { color: #4F46E5; font-size: 26px; font-weight: 900; letter-spacing: -1px; }

    div.stButton > button {
        background: white; border: 1px solid #E2E8F0;
        border-radius: 18px; color: #1E293B; height: 110px; width: 100%;
        font-weight: 700; font-size: 17px; transition: 0.4s cubic-bezier(0.4, 0, 0.2, 1);
    }
    div.stButton > button:hover {
        background: #4F46E5; color: white; transform: translateY(-6px);
        box-shadow: 0 15px 30px rgba(79, 70, 229, 0.25); border-color: #4F46E5;
    }
    .main .block-container { padding-top: 100px; }
    </style>
    
    <div class="navbar">
        <div class="spinning-logo"></div>
        <div class="brand">Aura AI</div>
    </div>
""", unsafe_allow_html=True)

# --- APP LOGIC & ROUTING ---
if 'page' not in st.session_state: 
    st.session_state.page = 'Dashboard'
if 'key' not in st.session_state: 
    try:
        st.session_state.key = st.secrets["api_key"]
    except:
        st.session_state.key = ""

def run_ai(prompt, instruction):
    if not st.session_state.key:
        return "⚠️ Error: Please enter your Google API Key in the sidebar."
    try:
        genai.configure(api_key=st.session_state.key)
        model = genai.GenerativeModel(model_name=MODEL_NAME, system_instruction=instruction)
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        if "429" in str(e): 
            return "⏳ System Busy. Google's Free Tier is rate-limited. Wait 60s."
        return f"❌ Error: {str(e)}"

# --- SIDEBAR ---
with st.sidebar:
    st.title("⚙️ Settings")
    input_key = st.text_input("Gemini API Key", value=st.session_state.key, type="password")
    if input_key: 
        st.session_state.key = input_key
    st.divider()
    if st.button("🏠 Back to Dashboard"): 
        st.session_state.page = 'Dashboard'
        st.rerun()

# --- VIEWS ---
tools = {
    "AI Detector": "Analyze text for AI patterns. Provide a probability score.",
    "Humanizer": "Rewrite text to sound 100% human. Vary sentence length and use natural idioms.",
    "Summarizer": "Summarize into 3 bullet points.",
    "Grammar": "Fix all errors. Output corrected text only.",
    "AI Chat": "You are Aura, a brilliant SaaS assistant.",
    "Translator": "Translate to English, or Spanish if already English.",
    "Paraphraser": "Rephrase creatively while keeping the meaning.",
    "Plagiarism": "Act as a text originality analyzer.",
    "Citations": "Generate APA/MLA citations for the provided source.",
    "Image Gen": "POLLINATIONS"
}

if st.session_state.page == 'Dashboard':
    st.markdown("## 🌌 Your AI Workspace")
    t_list = list(tools.keys())
    for r in range(0, 10, 5):
        cols = st.columns(5)
        for i in range(5):
            with cols[i]:
                if st.button(t_list[r+i]):
                    st.session_state.page = t_list[r+i]
                    st.rerun()
else:
    current = st.session_state.page
    st.subheader(f"Tool: {current}")
    user_input = st.text_area("Input Area", height=250, placeholder=f"Enter text for {current}...")
    
    if st.button(f"✨ Run {current}", type="primary"):
        if not user_input: 
            st.warning("Please enter text.")
        else:
            with st.spinner("Processing..."):
                if current == "Image Gen":
                    url = f"https://image.pollinations.ai/prompt/{urllib.parse.quote(user_input)}?nologo=true"
                    st.image(url, caption="Generated by Aura AI", use_container_width=True)
                else:
                    inst = tools[current]
                    res = run_ai(user_input, inst)
                    st.markdown("### Result")
                    st.info(res)
